from .auth import bp as auth_bp
from .users import bp as users_bp
from .buildings import bp as buildings_bp
from .rooms import bp as rooms_bp
from .courses import bp as courses_bp
from .students import bp as students_bp
from .assignments import bp as assignments_bp
from .assignments import bp as assign_bp
from .schedules import bp as schedules_bp
from .system import bp as system_bp
from .imports import bp as imports_bp
from .notifications import bp as notifications_bp
from .dashboard import bp as dashboard_bp
from .algorithms import bp as algorithms_bp
from .exams import bp as exams_bp
